# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#
# i3 config file (v4)
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

#startup compton
exec --no-startup-id compton 

#networkmanager
exec --no-startup-id NetworkManager
exec --no-startup-id nm-applet

#set keyboard layout
exec --no-startup-id "setxkbmap -layout us,am -option 'grp:alt_shift_toggle'"

#screen brightness
exec --no-startup-id xbacklight -set 60
bindsym XF86MonBrightnessUp exec xbacklight -inc 20
bindsym XF86MonBrightnessDown exec xbacklight -dec 20

#audio volume control 
bindsym XF86AudioRaiseVolume exec "amixer -q sset Master,0 5+ unmute"
bindsym XF86AudioLowerVolume exec "amixer -q sset Master,0 5- unmute"
bindsym XF86AudioMute exec "amixer -q sset Master,0 toggle"

#screenshot
exec --no-startup-id flameshot
bindsym Print exec "flameshot gui"

#wallpaper
exec --no-startup-id hsetroot -solid "#777777"

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

#urxvt 
exec --no-startup-id xrdb ~/.Xrecources

# font
font pango:DejaVu Sans Mono 8

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu 
bindsym $mod+d exec dmenu_run

# move focus 
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# workspace names
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

#i3
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exit

bindsym $mod+r mode "resize"
mode "resize" {
        
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bar {
	position top 
        status_command i3status
        font pango: mono 10
	mode dock	
}

bindsym $mod+Shift+f exec firefox
bindsym $mod+Shift+z exec zathura
bindsym $mod+Shift+t exec transmission-gtk
bindsym $mod+Shift+s exec scribus
bindsym $mod+Shift+i exec inkscape
bindsym $mod+Shift+g exec gimp

#lock
bindsym $mod+Ctrl+Delete exec i3lock -c 000000 && sleep 1s && systemctl suspend
bindsym $mod+Shift+Delete exec i3lock -c 777777

focus_follows_mouse no
